created new endpoint to get all admin users
Code-4-Community/jpal-backend pull request #14
Opened 2021-09-26 19:01 UTC by djung335

created a new get endpoint to return all users with the admin role!

2021-09-27 22:30 UTC, onb6 commented on src/users/users.service.ts
> +    console.log(
You can remove this console.log, in general we don't want console statements in our code so in the future if you use them for debugging purposes, make sure to delete them when you are done

2021-09-27 22:31 UTC, onb6 commented on src/users/users.service.ts
> +  async getAllAdmins(): Promise<User[]> {
Can you add a JS doc comment to describe what this function does. I know the others don't have this but I want to standardize this going forward

2021-09-27 22:33 UTC, onb6 reviewed
Left a few comments, once those small things are fixed this should be good to go! Great work on this!!

2021-09-27 23:40 UTC, djung335 commented on src/users/users.service.ts
> +  async getAllAdmins(): Promise<User[]> {
feedback implemented!

2021-09-27 23:40 UTC, djung335 commented on src/users/users.service.ts
> +    console.log(
feedback implemented!

2021-09-27 23:42 UTC, onb6 approved these changes
Woot!

2021-09-28 00:36 UTC, rymaju requested changes
Gonna be pedantic and ask for a nicer purpose statement, otherwise looks good!

2021-09-28 00:36 UTC, rymaju commented on src/users/users.service.ts
> +   *
⛏️ Can we remove this blank line 😅 
```suggestion
```

2021-09-28 00:36 UTC, rymaju commented on src/users/users.service.ts
> +   * grabs all users with the role admin and returns them as an array of Users
🔧 This isn't a great purpose statement, it more or less restates the signature and the name of the function. How about:

```suggestion
   * Finds all users with the admin role.
```

2021-09-28 00:36 UTC, rymaju commented on test/users.e2e-spec.ts
>      await usersRepository.clear();
🤔 Might be merge conflicts with @onb6 's PR

2021-09-28 01:01 UTC, djung335 commented on src/users/users.service.ts
> +   *
yes sir

2021-09-28 01:02 UTC, djung335 commented on src/users/users.service.ts
> +   * grabs all users with the role admin and returns them as an array of Users
I'll try and write better purpose statements next time

2021-09-28 01:02 UTC, djung335 commented on test/users.e2e-spec.ts
>      await usersRepository.clear();
uh oh

2021-09-29 16:16 UTC, onb6 commented on test/users.e2e-spec.ts
>      await usersRepository.clear();
It should be fine, I can help with resolving those if necessary.

2021-09-29 16:32 UTC, rymaju approved these changes
LGTM 💯 
Fix merge conflcits and we should be good

2021-09-30 00:49 UTC, merged