Create POST /survey
Code-4-Community/jpal-backend pull request #20
Opened 2021-10-03 20:27 UTC by wwohlers

2021-10-05 22:03 UTC, rymaju requested changes
Looks good, just want a few tiny fixes before this can get merged

2021-10-05 22:03 UTC, rymaju commented on src/survey/dto/create-survey.dto.ts
> +}
⛏️ Add a newline here

2021-10-05 22:03 UTC, rymaju commented on src/assignment/types/assignment.entity.ts
> +  uuid: string;
❓ Is there a UUID decorator we can use here?

2021-10-05 22:03 UTC, rymaju commented on src/survey/survey.service.spec.ts
> +  create(Survey?: DeepPartial<Survey> | DeepPartial<Survey>[]): any {
🔧 Can we use lowercase s `survey` please?

2021-10-05 22:03 UTC, rymaju commented on src/survey/survey.service.spec.ts
> +    return {
🔧 There are some eslint unused variable warnings here, can we remove those and get rid of those warnings?

2021-10-05 22:32 UTC, rymaju commented
Also, pretty sure tests are failing because the survey module is missing the TypeORM repository imports, should be something like:
```
@Module({
  imports: [TypeOrmModule.forFeature([Survey]), TypeOrmModule.forFeature([SurveyTemplate])],
  providers: [...],
  exports: [...],
})

```

2021-10-05 22:33 UTC, onb6 commented on src/assignment/types/assignment.entity.ts
> +  @ManyToOne(() => Reviewer)
Copy paste error, should be () => Survey

2021-10-05 22:36 UTC, onb6 requested changes
Overall this is great, left a comment about one small thing and agree w Ryans comments.

2021-10-10 19:30 UTC, wwohlers commented on src/assignment/types/assignment.entity.ts
> +  uuid: string;
There is, but only to auto-generate a UUID -- not sure if that's what we want?

2021-10-10 20:15 UTC, rymaju approved these changes
LGTM 💯

2021-10-10 20:15 UTC, rymaju commented on src/assignment/types/assignment.entity.ts
> +  uuid: string;
I think that makes sense! We need to generate one anyway, if it can do it for us then it sounds great. The only drawback I can see is that it tightly couples us to the UUID implementation, if we wanted to change it for some reason (maybe to make links look nicer) then it would be more painful.

2021-10-10 20:18 UTC, onb6 approved these changes
🤠

2021-10-10 20:23 UTC, merged