Create get survey
Code-4-Community/jpal-backend pull request #25
Opened 2021-10-15 22:35 UTC by djung335

There's kinda a lot going on here but this started as a ticket for an assignment get request and then somehow became a survey get request ticket, which is why all the files in the assignment file are commented out.

Basically, this push implements the request to get all the surveys created by the current user.

2021-10-16 01:58 UTC, rymaju requested changes

2021-10-16 01:58 UTC, rymaju commented on src/survey/survey.controller.ts
> +  getAllSurveys(@ReqUser() user: User): Promise<Survey[]> {
Does this follow the idiomatic NestJS naming conventions? I believe this should be `findAll`, please use the CLI to generate modules in the future.

Relevant docs:
https://docs.nestjs.com/controllers
https://docs.nestjs.com/providers
https://docs.nestjs.com/modules
https://docs.nestjs.com/cli/overview#command-overview

2021-10-16 01:58 UTC, rymaju commented on src/survey/survey.service.ts
> +  async getAllSurveys(user: User): Promise<Survey[]> {
⛏️ Same as above, I would prefer `findAll` and be consistent with NestJS naming conventions IMO

2021-10-17 18:41 UTC, wwohlers approved these changes
Just small stuff, like Ryan said please remove commented out code. In general PRs should be as small as possible.

2021-10-17 18:41 UTC, wwohlers commented on src/survey/survey.controller.spec.ts
> +    expect.assertions(2);
I believe expect.assertions is not necessary unless we have a try/catch block (or otherwise testing the rejection of promises). In this case it doesn't have any effect

2021-10-17 18:41 UTC, wwohlers commented on src/survey/survey.service.spec.ts
> +    expect.assertions(1);
See above

2021-10-30 13:44 UTC, rymaju approved these changes
LGTM

2021-10-31 00:34 UTC, merged