Am get survey endpoint
Code-4-Community/jpal-backend pull request #27
Opened 2021-10-31 19:05 UTC by atulyamiglani

``` /survey/:uuid ``` endpoint.

2021-10-31 19:17 UTC, djung335 reviewed
Just wondering, is package-lock json something that should be committed? I was under the assumption that it isn't along with settings.json, but I'd confirm with Olivia or Ryan.

2021-10-31 20:01 UTC, rymaju reviewed
Ill leave a couple more comments on style when I get home but its mostly pretty good. We can pair if needed.

2021-10-31 20:01 UTC, rymaju commented on test/survey.e2e-spec.ts
> +    expect(await surveyRepository.find()).toEqual([expected]);
This line made sense for the creation E2E because it was checking for an E2E side effect. For getting a single survey it doesnt really matter.

Instead, you should assert the response body equals the survey that you expect!

2021-10-31 20:04 UTC, atulyamiglani commented on src/survey/survey.service.ts
> +    return res[0];
My test was failing when I was using 'findOne' or 'findOneOrFail' 😔

2021-10-31 20:42 UTC, atulyamiglani commented on test/survey.e2e-spec.ts
> +    expect(await surveyRepository.find()).toEqual([expected]);
done!

2021-10-31 23:01 UTC, rymaju requested changes
Need to findOneOrFail, currently when no entity is found it will just return undefined.

2021-10-31 23:04 UTC, rymaju commented
> 
> 
> Just wondering, is package-lock json something that should be committed? I was under the assumption that it isn't along with settings.json, but I'd confirm with Olivia or Ryan.

If you are updating/adding a dependency you must commit both package files. Otherwise, they should be unchanged. We are using lockfile v2, so if you are using an old version of npm it may generate a downgraded version. In that case, you should revert the changes and upgrade npm to v7 in order to avoid that from happening again.

2021-11-01 00:35 UTC, atulyamiglani commented on src/survey/survey.service.ts
> +  async getSurveyByUUID(uuid: string) {
So the type should be ``` Promise<Survey> | undefined ```?

2021-11-01 00:36 UTC, atulyamiglani commented on package-lock.json
> +      "name": "jpal-backend",
lol I have no clue, I'll manually delete that line.

2021-11-07 20:46 UTC, onb6 commented on src/survey/survey.controller.spec.ts
> +    const survey = await controller.getByUUID(UUID);
I think this is supposed to be lowercase uuid, since it says uuid is defined but never used

2021-11-07 20:53 UTC, onb6 requested changes
Left one comment, but once that small change is made I think this is good to go!

2021-11-14 20:28 UTC, rymaju approved these changes
Looks GREAT!

2021-11-14 21:05 UTC, onb6 approved these changes
Looks great!

2021-11-14 21:07 UTC, merged