get survey for reviewer endpoint
Code-4-Community/jpal-backend pull request #34
Opened 2021-12-24 19:25 UTC by atulyamiglani

- gets the survey from its UUID and filters it for a specific reviewer.

2021-12-24 21:29 UTC, rymaju requested changes

2021-12-24 21:29 UTC, rymaju commented on test/e2e/survey.e2e-spec.ts
> +    expect(response.body).toEqual(expected);
The response doesnt contain any assignments, which is incorrect behavior right? How is the reviewer going to review any youth if it isnt given the assignments? This also needs to fit the frontend specification, not return the whole survey entity.

2021-12-24 22:04 UTC, atulyamiglani commented on test/e2e/survey.e2e-spec.ts
> +    expect(response.body).toEqual(expected);
No? it should not have any assignments because the reviewer of the assignment has UUID2 as their uuid. But this test is for ``` /survey/${UUID2}/${UUID} ``` so we want surveys that have reviewers UUID and not UUID2, which is none in this case? Does that make sense?

2021-12-24 22:05 UTC, rymaju requested changes
Theres a few things in here that don't really make sense to me, or at least I don't get yet. Should probably get on a call with @onb6 to sort this out when there's time.

Also, the frontend expects a response with this shape:


(from https://github.com/Code-4-Community/jpal-frontend/pull/59)

GET `/survey/:surveyUuid/:reviewerUuid`

Response is a `SurveyData`. (definitions below)
```ts
// from survey-assignment.dto.ts
export interface SurveyData {
  reviewer: Reviewer;
  controlYouth: Youth[];
  treatmentYouth: Youth[];
  questions: Question[];
}

export interface Question {
  question: string;
  options: string[];
}

export interface Youth extends PersonInfo {
  assignmentUuid: string;
}

export type Reviewer = PersonInfo;

interface PersonInfo {
  email: string;
  firstName: string;
  lastName: string;
}
```

2021-12-24 22:05 UTC, rymaju commented on src/survey/survey.service.ts
> +    const survey = await this.getByUUID(surveyUUID);
Will currently throw a TypeORM error which is translated to a `500` since this uses `findOneOrFail`, first check if it exists using `.find` then if undefined throw a `BadRequestException` (`400`) instead. Should be done on the controller level.

2021-12-24 22:05 UTC, rymaju commented on test/e2e/survey.e2e-spec.ts
> +      assignments: [mockAssignment],
Can the same assignment belong to two `Survey`s?

2021-12-24 22:05 UTC, rymaju commented on test/e2e/survey.e2e-spec.ts
> +      .set('Authorization', `Bearer ${JSON.stringify({ email: 'something@test.com' })}`);
No need for this line since this endpoint is public and does not require authorization.

2021-12-24 22:06 UTC, rymaju commented
Also in the future can you add more detail to your PR? Its difficult to understand all the changes you made when I only have one sentence of context.

2021-12-25 01:44 UTC, rymaju commented on test/e2e/survey.e2e-spec.ts
> +    expect(response.body).toEqual(expected);
No not really, I dont see how it is valid to ever return a survey with undefined assignments with a 200 OK. This seems like invalid data because theres nothing for the reviewer to review. Can you clarify?

2022-02-09 02:34 UTC, rymaju approved these changes
This has caused so much pain. Let it be done. 🔥 🚢 🔥

2022-02-09 03:03 UTC, djung335 approved these changes
looks absolutely splendid

2022-02-11 15:10 UTC, onb6 commented on src/survey/survey.service.ts
> +  transformToFrontendSurveyData(
I am so sorry. This is beautiful

2022-02-11 15:18 UTC, onb6 approved these changes
It is beautiful, I am so sorry for the pain it caused

2022-02-13 04:04 UTC, merged