fixed bug
Code-4-Community/jpal-backend pull request #50
Opened 2022-03-14 22:47 UTC by djung335

### ℹ️ Issue: Backend: bug in complete assignment

Closes [clickup ticket link](https://app.clickup.com/t/2h04t15)

- Added a simple if statement to check if an assignment's responses length were ever zero, and if so marks the assignment as complete and saves it in the repository.

2022-03-22 01:28 UTC, onb6 approved these changes
lgtm!

2022-03-27 19:24 UTC, rymaju requested changes

2022-03-27 19:24 UTC, rymaju commented on src/assignment/assignment.service.ts
> +      assignment.status == AssignmentStatus.COMPLETED;
```suggestion
      assignment.status = AssignmentStatus.COMPLETED;
```

2022-04-21 21:38 UTC, rymaju approved these changes
LGTM

2022-04-28 02:15 UTC, merged