Send emails with survey link on patch survey
Code-4-Community/jpal-backend pull request #52
Opened 2022-04-04 18:35 UTC by vrautela

### ℹ️ Issue

Closes [clickup ticket link](https://app.clickup.com/t/1hh69ca)

### 📝 Description

- Added SurveyService.sendEmailToReviewersInBatchAssignment method which uses the EmailService to send emails containing the survey links to each of the reviewers in a batch assignment
- Added helper methods for the above method
- Added controller logic to call the above method on a PATCH request to /survey after calling SurveyService.createBatchAssignments

### ✔️ Verification

I used Postman to create a PATCH request to /survey with two pairs (of youth and reviewer). I verified that the assignment was created in the DB and that both reviewer accounts received emails.

Automated tests are coming soon. There is a weird test failure that I'm trying to figure out.

![image](https://user-images.githubusercontent.com/16907452/161608193-6615ea1b-6ccc-4849-a81f-bf4c92087088.png)

### 🏕️ (Optional) Future Work / Notes

The SurveyService.createBatchAssignments method errors when given youths or reviewers that already exist. Is that intentional? (It's because of a constraint on the youth and reviewer tables in the DB and the fact that the method saves each of the youths and reviewers in the createBatchAssignmentsDto)

2022-04-04 21:52 UTC, wwohlers requested changes
Good start, some promise stuff to make this faster and other minor fixes

2022-04-04 21:52 UTC, wwohlers commented on src/survey/survey.controller.ts
> +    await this.surveyService.sendEmailToReviewersInBatchAssignment(createBatchAssignmentsDto);
We should use Promise.all here to do these simultaneously

2022-04-04 21:52 UTC, wwohlers commented on src/survey/survey.service.ts
> +    for (const pair of createBatchAssignmentsDto.pairs) {
Again, we should use Promise.all and map over `createBatchAssignmentsDto.pairs` to do this all simultaneously

2022-04-04 21:52 UTC, wwohlers commented on src/survey/survey.service.ts
> +    const link: string = `${domain}/survey/${surveyUUID}/${reviewerUUID}`;
Remove the type declarations on 116 and 117, not necessary

2022-04-04 21:52 UTC, wwohlers commented on src/survey/survey.service.ts
> +      const emailBodyHTML: string = this.generateEmailBodyHTML(createBatchAssignmentsDto.surveyUUID, reviewer.uuid)
Remove type declarations on 101 and 102, unnecessary

2022-04-10 18:39 UTC, vrautela commented on src/survey/survey.service.ts
> +      const emailBodyHTML: string = this.generateEmailBodyHTML(createBatchAssignmentsDto.surveyUUID, reviewer.uuid)
I'm gonna keep it for documentation reasons

2022-04-10 23:42 UTC, vrautela commented on src/survey/survey.controller.ts
> +    await this.surveyService.sendEmailToReviewersInBatchAssignment(createBatchAssignmentsDto);
It seems like a bad idea to send emails to reviewers if the creation of the batch assignments fails, so I'm going to change the logic here so that surveyService.createBatchAssignments calls the sendEmailToReviewersInBatchAssignment method after creating the batch assignments

2022-04-19 15:13 UTC, onb6 commented on src/survey/survey.service.ts
> +        const reviewer: Reviewer = await this.reviewerRepository.findOneOrFail({firstName: reviewerInfo.firstName, lastName: reviewerInfo.lastName})
Can we do FindOne here and manually throw a bad request exception. Findoneoffail throws an internal server error which we want to avoid

2022-04-19 15:14 UTC, onb6 commented on src/survey/survey.service.ts
> +   * Returns the subject line of the email sent to reviewers
I like having these as separate functions, very nice!

2022-04-19 15:15 UTC, onb6 requested changes

2022-04-19 15:15 UTC, onb6 commented on src/survey/survey.service.ts
> +        const reviewer: Reviewer = await this.reviewerRepository.findOneOrFail({firstName: reviewerInfo.firstName, lastName: reviewerInfo.lastName})
Can we do FindOne here and manually throw a bad request exception. Findoneoffail throws an internal server error which we want to avoid

2022-04-26 01:06 UTC, rymaju approved these changes
LGTM

2022-04-30 20:07 UTC, onb6 approved these changes
LGTM!

2022-04-30 20:08 UTC, onb6 commented
Oh  also it looks like you still have one src/.. import in your e2e test that is causing the tests to fail

2022-05-01 20:35 UTC, wwohlers approved these changes

2022-05-11 17:06 UTC, merged