Randomize control
Code-4-Community/jpal-backend pull request #73
Opened 2023-02-21 23:58 UTC by Dhivas-Sugumar

### ℹ️ Issue

Closes https://app.clickup.com/t/25czvgu

### 📝 Description

Briefly list the changes made to the code:

- Added support for randomly assigning control and treatment.

### ✔️ Verification

Not really sure how to verify this. 

### 🏕️ (Optional) Future Work / Notes

Did you notice anything ugly during the course of this ticket? Any bugs, design challenges, or unexpected behavior? Write it down so we can clean it up in a future ticket!

2023-03-03 20:52 UTC, rymaju commented
@Dhivas-Sugumar 
1. Please try to get in the habit of small commits with good names! `I think this should work` isn't great!
2. "Added support for randomly assigning control and treatment.", How exactly? The point of the itemization is that you can add detailed and informative points for reviewers!

2023-03-03 20:53 UTC, rymaju commented
Also, run prettier

2023-03-03 20:59 UTC, rymaju requested changes

2023-03-03 20:59 UTC, rymaju commented on src/survey/survey.service.ts
> +    shuffleArray();
This is incredibly important code. Assigning control/experimental groups incorrectly could invalidate the entire experiment!

If we are doing this manually, where are the tests, how are you ensuring this is truly random?

And why are we doing this manually? This feels like exactly the kind of critical complexity to delegate to a trusted library.

2023-03-03 20:59 UTC, rymaju commented on src/survey/survey.service.ts
> +    const [youth, reviewers] = await Promise.all([ // Split here
```suggestion
    const [youth, reviewers] = await Promise.all([
```

2023-03-03 20:59 UTC, rymaju commented on src/survey/survey.service.ts
> +        index % 2 == 0 ? p.youth.role = YouthRoles.CONTROL : p.youth.role = YouthRoles.TREATMENT
Suppose JPAL decides that they want to split experimental and control groups 60:40, how would you change this code?

Odd/even with modulo is hard to read, split it into two lists rather than a nested map within a function call.

2023-03-03 20:59 UTC, rymaju commented on src/survey/survey.service.ts
> +      this.youthRepository.save(pairArray.map((p, index) =>  {
🔧 ‼️ `.save` returns a promise, this code wont finish saving all the youth before this handler returns

2023-03-03 20:59 UTC, rymaju commented on src/survey/survey.service.ts
> +      this.reviewerRepository.save(pairArray.map((p) => p.reviewer)),
🔧 ‼️ `.save` returns a promise, this code wont finish saving all the reviewers before this handler returns

2023-03-03 22:07 UTC, Dhivas-Sugumar commented on src/survey/survey.service.ts
> +    shuffleArray();
> @Dhivas-Sugumar
> 
> 1. Please try to get in the habit of small commits with good names! `I think this should work` isn't great!
> 2. "Added support for randomly assigning control and treatment.", How exactly? The point of the itemization is that you can add detailed and informative points for reviewers!

1. Will keep this in mind, when I make commits in the future.

2023-03-03 22:09 UTC, Dhivas-Sugumar commented on src/survey/survey.service.ts
> +    shuffleArray();
2. I use the fisher yates shuffle algorithm that shuffles the items in an array, i.e changes the order. Here is a link for it https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle. To me this seemed like a good option instead of adding a library to do this. Then assign using index for a 50-50 split.

2023-03-03 22:12 UTC, Dhivas-Sugumar commented on src/survey/survey.service.ts
> +        index % 2 == 0 ? p.youth.role = YouthRoles.CONTROL : p.youth.role = YouthRoles.TREATMENT
Good point. I will refactor the code to handle custom splits. I'll make a function that takes a shuffled list using the shuffle algorithm. Might need to think about how to do a custom split. My first thought is that since it is a randomized list already I can do a 60 / 40 split on the list, but maybe there is a better way to achieve randomness better.

2023-03-03 22:12 UTC, Dhivas-Sugumar commented on src/survey/survey.service.ts
> +      this.reviewerRepository.save(pairArray.map((p) => p.reviewer)),
will fix this when I get to it. that was an oversight on my part.

2023-04-23 04:16 UTC, rymaju commented
Closed due to inactivity

2023-04-23 04:16 UTC, closed without merging